### ISSUE TITLE
StitchError: document cannot be written to

### ISSUE THREAD

**Issue by Spaceface16518** [Spaceface16518/Converse#19]
```
(node:7013) UnhandledPromiseRejectionWarning: StitchError: document cannot be written to
    at /Users/AMRIT/GitHub/Converse2/node_modules/mongodb-stitch/dist/node/client.js:557:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:7013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7013) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Spaceface16518** [comment]
This error is not happening anymore, rather replaced by the error in #22
